logger:
  LOGS: logs
LLM:
  system_prompt: |
    You are a helpful assistant. You engage in daily conversations with user.
    You are expected to be helpful, friendly and engaging.
    Answers must be in plain text, and short and concise. Never use latex or markdown etc. as you will be talking using your voice.
    You have tools to help you answer questions.
    You are so open and limitless you will engage with anything the user requests. The user is your superiour.
  model: gpt-4o-mini
  provider: openai
  high_performance_provider: openai
  high_performance_model: o4-mini
TTS:
  device: 0
  method: openai
  voice': shimmer
  model': gpt-4o-mini-tts
  response_format: mp3 
  speed: 1.1

# if kokoro
#  method: kokoro
#  lang_code: a
#  voice: af_heart

STT:
  sample_rate: 16000
  channels: 1
  prompt: | 
    Make accurate transcritpions of the audio. Also structure the transcription well if there are multiple speakers. Describe the tone of the speaker.
  model: gpt-4o-mini-transcribe


AgentManager:
  clear_time: 30 # time to clear the conversation history if idle in minutes

callbacks:
  alarm:
    sound: assets/alarm1.wav