SpeechToText:
  ChunkSize: 4096
  Rate: 44100
  Channels: 1
  Threshold: 1250
  WaitTime: 50

  audio_path: /dev/audio/speech.wav


  Modes:
    local:

    groq:
      # nothing needed for groq now
  
  mode: 'groq' # local, groq

TTS:
  Modes:
    light:
      speaker_index: 7306
    mid:
      speaker_wav_path: 'dev/audio/mid_speaker_wav/female.wav'
      language: 'en'
    heavy:
      # nothing needed for heavy now
    api:
      voice: 'Salli'

  mode: 'api' # light, heavy, mid
  save_path: 'dev/audio/tts_output.wav'

LLMInference:
  # nothing needed for LLM now
  #TODO temp, max context length, system prompt, etc 
  history_path: 'history/helpful_standart_open.json' # history is not used with gemini now
  llm_host: 'gemini'
  llm_model: 'gemini-1.5-flash'
  tools: True # Tools are supported for groq llama and gemini models
EchoSee:
  # nothing needed for EchoSee now
